name: e_library
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  google_fonts: ^4.0.4
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  intl: ^0.18.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.6.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.10

  webview_flutter: ^4.2.0
  webview_flutter_wkwebview: ^3.4.2
  webview_flutter_platform_interface: ^2.3.0
  webview_flutter_android: ^3.7.0

  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bookmark.png
    - assets/bookmarked.png
    - assets/circular_main_icon.png
    - assets/completed.png
    - assets/epub_icon.png
    - assets/example_grid.png
    - assets/completed.png
    - assets/help_icon.png
    - assets/logout_icon.png
    - assets/main_icon.png
    - assets/no_cover.jpg
    - assets/no_epub_icon.png
    - assets/no_pdf_icon.png
    - assets/password_icon.png
    - assets/pdf_icon.png
    - assets/pencil_icon.png
    - assets/reading_icon.png
    - assets/removed_icon.png
    - assets/search_icon.png
    - assets/slider_1.jpg
    - assets/slider_2.jpg
    - assets/slider_3.jpg
    - assets/splash_screen_icon.png
    - assets/success_icon.png

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/inter/Inter-Black.tff
  #       - asset: fonts/inter/Inter-Bold.tff
  #       - asset: fonts/inter/Inter-ExtraBold.tff
  #       - asset: fonts/inter/Inter-ExtraLight.tff
  #       - asset: fonts/inter/Inter-Light.tff
  #       - asset: fonts/inter/Inter-Medium.tff
  #       - asset: fonts/inter/Inter-Regular.tff
  #       - asset: fonts/inter/Inter-SemiBold.tff
  #       - asset: fonts/inter/Inter-Thin.tff
        