// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnUlzPH5kNQn0s2lMWlwmbbogdR-80k0',
    appId: '1:542880158212:web:1a726b4ca3e25a1be91b51',
    messagingSenderId: '542880158212',
    projectId: 'e-library-d19ce',
    authDomain: 'e-library-d19ce.firebaseapp.com',
    storageBucket: 'e-library-d19ce.appspot.com',
    measurementId: 'G-29V398BP56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHR-EhbthklJ4myDVT77xYXEDFETn8-Uw',
    appId: '1:542880158212:android:ffa38dc66a3a4515e91b51',
    messagingSenderId: '542880158212',
    projectId: 'e-library-d19ce',
    storageBucket: 'e-library-d19ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlw6uMg3u1PrrqYcL64I3Fvw9-pelAyU',
    appId: '1:542880158212:ios:ae3131703696b21be91b51',
    messagingSenderId: '542880158212',
    projectId: 'e-library-d19ce',
    storageBucket: 'e-library-d19ce.appspot.com',
    iosClientId: '542880158212-3jtm1esc2lh6gqcvqnsurlmvh4sd7bu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlw6uMg3u1PrrqYcL64I3Fvw9-pelAyU',
    appId: '1:542880158212:ios:ae3131703696b21be91b51',
    messagingSenderId: '542880158212',
    projectId: 'e-library-d19ce',
    storageBucket: 'e-library-d19ce.appspot.com',
    iosClientId: '542880158212-3jtm1esc2lh6gqcvqnsurlmvh4sd7bu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLibrary',
  );
}
